version: "3.8"
services:
    debian:
        build:
            context: "./configure/debian"
            args:
                WEB_USER_GID: ${WEB_USER_GID}
                WEB_USER_UID: ${WEB_USER_UID}
                WEB_USER_PASSWORD: ${WEB_USER_PASSWORD}
        restart: "always"
        ports:
            - "80:80"
            - "443:443"
        environment:
            - "TZ=Asia/Seoul"
            - "DEBIAN_FRONTEND=noninteractive"
        volumes:
            - "./sources/web:/Application:rw"
        depends_on:
            - "mariadb"
    mariadb:
        build:
            context: "./configure/mariadb"
            args:
                MYSQL_UID: ${MYSQL_UID}
                MYSQL_GID: ${MYSQL_GID}
        user: "${MYSQL_UID}:${MYSQL_GID}"
        restart: "always"
        ports:
            - "3306:3306"
        environment:
            - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
            - "MYSQL_DATABASE=${MYSQL_DATABASE}"
            - "MYSQL_USER=${MYSQL_USER}"
            - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
        volumes:
            - "./sources/mariadb:/var/lib/mysql:rw"